export const fakeIssues = [
  {
    "url": "https://api.github.com/repos/octocat/Hello-World/issues/332",
    "repository_url": "https://api.github.com/repos/octocat/Hello-World",
    "labels_url": "https://api.github.com/repos/octocat/Hello-World/issues/332/labels{/name}",
    "comments_url": "https://api.github.com/repos/octocat/Hello-World/issues/332/comments",
    "events_url": "https://api.github.com/repos/octocat/Hello-World/issues/332/events",
    "html_url": "https://github.com/octocat/Hello-World/issues/332",
    "id": 216325558,
    "number": 332,
    "title": "Found a bug",
    "user": {
      "login": "ram619prasad",
      "id": 8692347,
      "avatar_url": "https://avatars3.githubusercontent.com/u/8692347?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ram619prasad",
      "html_url": "https://github.com/ram619prasad",
      "followers_url": "https://api.github.com/users/ram619prasad/followers",
      "following_url": "https://api.github.com/users/ram619prasad/following{/other_user}",
      "gists_url": "https://api.github.com/users/ram619prasad/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ram619prasad/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ram619prasad/subscriptions",
      "organizations_url": "https://api.github.com/users/ram619prasad/orgs",
      "repos_url": "https://api.github.com/users/ram619prasad/repos",
      "events_url": "https://api.github.com/users/ram619prasad/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ram619prasad/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "close",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 1,
    "created_at": "2017-03-23T07:04:41Z",
    "updated_at": "2017-03-25T20:33:27Z",
    "closed_at": null,
    "body": "I'm having a problem with this."
  },
  {
    "url": "https://api.github.com/repos/octocat/Hello-World/issues/331",
    "repository_url": "https://api.github.com/repos/octocat/Hello-World",
    "labels_url": "https://api.github.com/repos/octocat/Hello-World/issues/331/labels{/name}",
    "comments_url": "https://api.github.com/repos/octocat/Hello-World/issues/331/comments",
    "events_url": "https://api.github.com/repos/octocat/Hello-World/issues/331/events",
    "html_url": "https://github.com/octocat/Hello-World/pull/331",
    "id": 215767395,
    "number": 331,
    "title": "Update README",
    "user": {
      "login": "LaurMerl",
      "id": 16915243,
      "avatar_url": "https://avatars1.githubusercontent.com/u/16915243?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/LaurMerl",
      "html_url": "https://github.com/LaurMerl",
      "followers_url": "https://api.github.com/users/LaurMerl/followers",
      "following_url": "https://api.github.com/users/LaurMerl/following{/other_user}",
      "gists_url": "https://api.github.com/users/LaurMerl/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/LaurMerl/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/LaurMerl/subscriptions",
      "organizations_url": "https://api.github.com/users/LaurMerl/orgs",
      "repos_url": "https://api.github.com/users/LaurMerl/repos",
      "events_url": "https://api.github.com/users/LaurMerl/events{/privacy}",
      "received_events_url": "https://api.github.com/users/LaurMerl/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 0,
    "created_at": "2017-03-21T14:54:36Z",
    "updated_at": "2017-03-21T14:54:36Z",
    "closed_at": null,
    "pull_request": {
      "url": "https://api.github.com/repos/octocat/Hello-World/pulls/331",
      "html_url": "https://github.com/octocat/Hello-World/pull/331",
      "diff_url": "https://github.com/octocat/Hello-World/pull/331.diff",
      "patch_url": "https://github.com/octocat/Hello-World/pull/331.patch"
    },
    "body": ""
  }
]

export const fakeRepos = {
  "total_count": 1096,
  "incomplete_results": false,
  "items": [
    {
      "id": 2096579,
      "name": "marked",
      "full_name": "chjj/marked",
      "owner": {
        "login": "chjj",
        "id": 470564,
        "avatar_url": "https://avatars1.githubusercontent.com/u/470564?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/chjj",
        "html_url": "https://github.com/chjj",
        "followers_url": "https://api.github.com/users/chjj/followers",
        "following_url": "https://api.github.com/users/chjj/following{/other_user}",
        "gists_url": "https://api.github.com/users/chjj/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/chjj/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/chjj/subscriptions",
        "organizations_url": "https://api.github.com/users/chjj/orgs",
        "repos_url": "https://api.github.com/users/chjj/repos",
        "events_url": "https://api.github.com/users/chjj/events{/privacy}",
        "received_events_url": "https://api.github.com/users/chjj/received_events",
        "type": "User",
        "site_admin": false
      },
      "private": false,
      "html_url": "https://github.com/chjj/marked",
      "description": "A markdown parser and compiler. Built for speed.",
      "fork": false,
      "url": "https://api.github.com/repos/chjj/marked",
      "forks_url": "https://api.github.com/repos/chjj/marked/forks",
      "keys_url": "https://api.github.com/repos/chjj/marked/keys{/key_id}",
      "collaborators_url": "https://api.github.com/repos/chjj/marked/collaborators{/collaborator}",
      "teams_url": "https://api.github.com/repos/chjj/marked/teams",
      "hooks_url": "https://api.github.com/repos/chjj/marked/hooks",
      "issue_events_url": "https://api.github.com/repos/chjj/marked/issues/events{/number}",
      "events_url": "https://api.github.com/repos/chjj/marked/events",
      "assignees_url": "https://api.github.com/repos/chjj/marked/assignees{/user}",
      "branches_url": "https://api.github.com/repos/chjj/marked/branches{/branch}",
      "tags_url": "https://api.github.com/repos/chjj/marked/tags",
      "blobs_url": "https://api.github.com/repos/chjj/marked/git/blobs{/sha}",
      "git_tags_url": "https://api.github.com/repos/chjj/marked/git/tags{/sha}",
      "git_refs_url": "https://api.github.com/repos/chjj/marked/git/refs{/sha}",
      "trees_url": "https://api.github.com/repos/chjj/marked/git/trees{/sha}",
      "statuses_url": "https://api.github.com/repos/chjj/marked/statuses/{sha}",
      "languages_url": "https://api.github.com/repos/chjj/marked/languages",
      "stargazers_url": "https://api.github.com/repos/chjj/marked/stargazers",
      "contributors_url": "https://api.github.com/repos/chjj/marked/contributors",
      "subscribers_url": "https://api.github.com/repos/chjj/marked/subscribers",
      "subscription_url": "https://api.github.com/repos/chjj/marked/subscription",
      "commits_url": "https://api.github.com/repos/chjj/marked/commits{/sha}",
      "git_commits_url": "https://api.github.com/repos/chjj/marked/git/commits{/sha}",
      "comments_url": "https://api.github.com/repos/chjj/marked/comments{/number}",
      "issue_comment_url": "https://api.github.com/repos/chjj/marked/issues/comments{/number}",
      "contents_url": "https://api.github.com/repos/chjj/marked/contents/{+path}",
      "compare_url": "https://api.github.com/repos/chjj/marked/compare/{base}...{head}",
      "merges_url": "https://api.github.com/repos/chjj/marked/merges",
      "archive_url": "https://api.github.com/repos/chjj/marked/{archive_format}{/ref}",
      "downloads_url": "https://api.github.com/repos/chjj/marked/downloads",
      "issues_url": "https://api.github.com/repos/chjj/marked/issues{/number}",
      "pulls_url": "https://api.github.com/repos/chjj/marked/pulls{/number}",
      "milestones_url": "https://api.github.com/repos/chjj/marked/milestones{/number}",
      "notifications_url": "https://api.github.com/repos/chjj/marked/notifications{?since,all,participating}",
      "labels_url": "https://api.github.com/repos/chjj/marked/labels{/name}",
      "releases_url": "https://api.github.com/repos/chjj/marked/releases{/id}",
      "deployments_url": "https://api.github.com/repos/chjj/marked/deployments",
      "created_at": "2011-07-24T13:15:51Z",
      "updated_at": "2017-03-31T19:34:22Z",
      "pushed_at": "2017-03-30T14:45:14Z",
      "git_url": "git://github.com/chjj/marked.git",
      "ssh_url": "git@github.com:chjj/marked.git",
      "clone_url": "https://github.com/chjj/marked.git",
      "svn_url": "https://github.com/chjj/marked",
      "homepage": "",
      "size": 611,
      "stargazers_count": 12327,
      "watchers_count": 12327,
      "language": "HTML",
      "has_issues": true,
      "has_projects": true,
      "has_downloads": true,
      "has_wiki": true,
      "has_pages": false,
      "forks_count": 1735,
      "mirror_url": null,
      "open_issues_count": 487,
      "forks": 1735,
      "open_issues": 487,
      "watchers": 12327,
      "default_branch": "master",
      "score": 119.044044
    },
    {
      "id": 14736952,
      "name": "MarkedCustomStyles",
      "full_name": "ttscoff/MarkedCustomStyles",
      "owner": {
        "login": "ttscoff",
        "id": 47833,
        "avatar_url": "https://avatars1.githubusercontent.com/u/47833?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ttscoff",
        "html_url": "https://github.com/ttscoff",
        "followers_url": "https://api.github.com/users/ttscoff/followers",
        "following_url": "https://api.github.com/users/ttscoff/following{/other_user}",
        "gists_url": "https://api.github.com/users/ttscoff/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/ttscoff/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ttscoff/subscriptions",
        "organizations_url": "https://api.github.com/users/ttscoff/orgs",
        "repos_url": "https://api.github.com/users/ttscoff/repos",
        "events_url": "https://api.github.com/users/ttscoff/events{/privacy}",
        "received_events_url": "https://api.github.com/users/ttscoff/received_events",
        "type": "User",
        "site_admin": false
      },
      "private": false,
      "html_url": "https://github.com/ttscoff/MarkedCustomStyles",
      "description": null,
      "fork": false,
      "url": "https://api.github.com/repos/ttscoff/MarkedCustomStyles",
      "forks_url": "https://api.github.com/repos/ttscoff/MarkedCustomStyles/forks",
      "keys_url": "https://api.github.com/repos/ttscoff/MarkedCustomStyles/keys{/key_id}",
      "collaborators_url": "https://api.github.com/repos/ttscoff/MarkedCustomStyles/collaborators{/collaborator}",
      "teams_url": "https://api.github.com/repos/ttscoff/MarkedCustomStyles/teams",
      "hooks_url": "https://api.github.com/repos/ttscoff/MarkedCustomStyles/hooks",
      "issue_events_url": "https://api.github.com/repos/ttscoff/MarkedCustomStyles/issues/events{/number}",
      "events_url": "https://api.github.com/repos/ttscoff/MarkedCustomStyles/events",
      "assignees_url": "https://api.github.com/repos/ttscoff/MarkedCustomStyles/assignees{/user}",
      "branches_url": "https://api.github.com/repos/ttscoff/MarkedCustomStyles/branches{/branch}",
      "tags_url": "https://api.github.com/repos/ttscoff/MarkedCustomStyles/tags",
      "blobs_url": "https://api.github.com/repos/ttscoff/MarkedCustomStyles/git/blobs{/sha}",
      "git_tags_url": "https://api.github.com/repos/ttscoff/MarkedCustomStyles/git/tags{/sha}",
      "git_refs_url": "https://api.github.com/repos/ttscoff/MarkedCustomStyles/git/refs{/sha}",
      "trees_url": "https://api.github.com/repos/ttscoff/MarkedCustomStyles/git/trees{/sha}",
      "statuses_url": "https://api.github.com/repos/ttscoff/MarkedCustomStyles/statuses/{sha}",
      "languages_url": "https://api.github.com/repos/ttscoff/MarkedCustomStyles/languages",
      "stargazers_url": "https://api.github.com/repos/ttscoff/MarkedCustomStyles/stargazers",
      "contributors_url": "https://api.github.com/repos/ttscoff/MarkedCustomStyles/contributors",
      "subscribers_url": "https://api.github.com/repos/ttscoff/MarkedCustomStyles/subscribers",
      "subscription_url": "https://api.github.com/repos/ttscoff/MarkedCustomStyles/subscription",
      "commits_url": "https://api.github.com/repos/ttscoff/MarkedCustomStyles/commits{/sha}",
      "git_commits_url": "https://api.github.com/repos/ttscoff/MarkedCustomStyles/git/commits{/sha}",
      "comments_url": "https://api.github.com/repos/ttscoff/MarkedCustomStyles/comments{/number}",
      "issue_comment_url": "https://api.github.com/repos/ttscoff/MarkedCustomStyles/issues/comments{/number}",
      "contents_url": "https://api.github.com/repos/ttscoff/MarkedCustomStyles/contents/{+path}",
      "compare_url": "https://api.github.com/repos/ttscoff/MarkedCustomStyles/compare/{base}...{head}",
      "merges_url": "https://api.github.com/repos/ttscoff/MarkedCustomStyles/merges",
      "archive_url": "https://api.github.com/repos/ttscoff/MarkedCustomStyles/{archive_format}{/ref}",
      "downloads_url": "https://api.github.com/repos/ttscoff/MarkedCustomStyles/downloads",
      "issues_url": "https://api.github.com/repos/ttscoff/MarkedCustomStyles/issues{/number}",
      "pulls_url": "https://api.github.com/repos/ttscoff/MarkedCustomStyles/pulls{/number}",
      "milestones_url": "https://api.github.com/repos/ttscoff/MarkedCustomStyles/milestones{/number}",
      "notifications_url": "https://api.github.com/repos/ttscoff/MarkedCustomStyles/notifications{?since,all,participating}",
      "labels_url": "https://api.github.com/repos/ttscoff/MarkedCustomStyles/labels{/name}",
      "releases_url": "https://api.github.com/repos/ttscoff/MarkedCustomStyles/releases{/id}",
      "deployments_url": "https://api.github.com/repos/ttscoff/MarkedCustomStyles/deployments",
      "created_at": "2013-11-27T04:01:09Z",
      "updated_at": "2017-03-31T11:27:32Z",
      "pushed_at": "2016-12-26T21:39:29Z",
      "git_url": "git://github.com/ttscoff/MarkedCustomStyles.git",
      "ssh_url": "git@github.com:ttscoff/MarkedCustomStyles.git",
      "clone_url": "https://github.com/ttscoff/MarkedCustomStyles.git",
      "svn_url": "https://github.com/ttscoff/MarkedCustomStyles",
      "homepage": null,
      "size": 2518,
      "stargazers_count": 265,
      "watchers_count": 265,
      "language": "CSS",
      "has_issues": true,
      "has_projects": true,
      "has_downloads": true,
      "has_wiki": true,
      "has_pages": false,
      "forks_count": 87,
      "mirror_url": null,
      "open_issues_count": 4,
      "forks": 87,
      "open_issues": 4,
      "watchers": 265,
      "default_branch": "master",
      "score": 36.174065
    }]
}